name: Unit Tests

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the develop branch
    push:
        branches: [ci/cd]
    pull_request:
        branches: [ci/cd]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2

            - name: Generating config.env
              run: |
                  touch config.env
                  echo "consumer_key = ${{ secrets.CONSUMER_KEY }}" >> config.env
                  echo "consumer_secret = ${{ secrets.CONSUMER_SECRET }}" >> config.env
                  echo "api_key = ${{ secrets.API_KEY }}" >> config.env
                  echo "callback_url = ${{ secrets.CALLBACK_URL }}" >> config.env

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.4

            - name: Install dependencies
              run: composer install

            - name: Run unit tests
              run: composer run unit-tests
